config/routes.rb
Rails.application.routes.draw do
  get 'feed' => 'epicenter#feed'

  get 'user_profile' => 'epicenter#show_user'

  post 'now_following' => 'epicenter#now_following'

  post 'unfollow' => 'epicenter#unfollow'

  resources :tweets

  devise_for :users

  root 'tweets#index'
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

	belongs_to :user

	validates :message, presence: true, length: {maximum: 140}
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  serialize :following, Array
  
  has_many :tweets

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	 protected

	 def configure_permitted_parameters

	   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
	     :name, :username, :bio, :location, :following) }

	   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
	     :current_password, :name, :username, :bio, :location, :following) }

	 end
  
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
  	@following_tweets = []

  	@tweets = Tweet.all

  	@tweets.each do |tweet|
  		if current_user.following.include?(tweet.user.id)
  			@following_tweets.push(tweet) 
  		end
  	end
  end

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	@user = User.find(params[:follow_id])

  	current_user.following.push(params[:follow_id].to_i)

  	current_user.save

    # redirect_to :controller => 'tweets', :action => :index
    
  end

  def unfollow
    @user = User.find(params[:unfollow_id])

    current_user.following.delete(params[:unfollow_id].to_i)

    current_user.save

    # redirect_to :controller => 'tweets', :action => :index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/epicenter/feed.html.erb
<h1>Your Twitter Feed</h1>
<p>Here's what your freinds are saying</p>

<div>
	<% @following_tweets.each do |tweet| %>
		<p>
			<strong><%= tweet.user.username %>:</strong> <br />
			<%= tweet.message %>
		</p>
	<% end %>
</div>

app/views/epicenter/now_following.html.erb
<p>You are now following: <%= @user.username %></p>

app/views/epicenter/show_user.html.erb
<h1><%= @user.username %></h1>
<h3><%= @user.location %></h3>
<h3>Bio:</h3>
<p><%= @user.bio %></p>

<div class="row">
 <% @user.tweets.each do |tweet| %>
   <div class="col-md-12">
       <div class="panel panel-default">
           <div class="panel-body">
           <p><%= tweet.message %></p>
           </div>
       </div>
   </div>
 <% end %>
</div>

<% if current_user.id != @user.id %>
  <% if current_user.following.include?(@user.id) %>
      <div>
        <%= form_tag('/unfollow') do %>
          <div class="cant-see-me">
            <%= number_field_tag :unfollow_id, @user.id %>
          </div>
        <%= submit_tag "Unfollow", class: "btn btn-primary", 
            id: "unfollow_btn"%>
        <% end %>
      </div>

  <% else %>
      <div>
      	<%= form_tag('/now_following') do %>
      		<div class="cant-see-me">
      			<%= number_field_tag :follow_id, @user.id %>
      		</div>
      		<%= submit_tag "Follow", class: "btn btn-primary" %>
      	<% end %>
      </div>
  <% end %>
<% end %>

<script>
  $(document).ready(function(){
    $('#follow_btn').hover(function(){
      $(this).removeClass("btn-primary");
      $(this).addClass("btn-danger");
      $(this).attr('value','Unfollow');
    }, function(){
      $(this).attr('value', 'Following');
      $(this).removeClass("btn-danger");
      $(this).addClass("btn-primary");
    });
  });
</script>

app/views/epicenter/unfollow.html.erb
<p>You're not following <%=@user.username %> anymore </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
 	  <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>TwitterLite</title>
  		<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"%>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"%>
		  <%= csrf_meta_tags %>
</head>

<body>
<% if user_signed_in? %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Tweets", tweets_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
       <li>Welcome <%= current_user.name %></li>
        <!-- Future Links! -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>
<% else %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Tweets", tweets_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up",  new_user_registration_path %></li>
        <li><%= link_to "Forgot Password",  new_user_password_path %></li>
      </ul>
    </div>
  </div>
</nav>
<% end %>



<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :message, placeholder: "What do you have to say?", class: "form-control" %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Tweet It!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to tweet.user.username, user_profile_path(id: tweet.user_id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, user_profile_path(id: @tweet.user.id)%>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

<p id="peek">Where</p>
<button type="button" id="showMe()">Where is he</button>
<br />
<p id="adding">What is 42 + 108?</p>
<button type="button" onclick="showSum(42, 108)">Add it!</button>
<br />
<br />
<p id="answer1">What does HTML stand for?</p>
<p id="answer2">What does CSS stand for?</p>
<br />
<p class = "paragraph1">This tex is only temp.</p>
<p class = "paragraph2">This is text. Say goodbye</p>
<button id ="change-paragraphs">Change It Up</button>


<script>
	function showMe(){
		document.getElementById('peek').innerHTML = "Here I am!";
	}

	function addItUp(x,y) {
		var sum = x + y;
		return sum;
	}

	function showSum(x,y) {
		document.getElementById('adding').innerHTML = addItUp();		
	}

	function htmlAcronym() {
		document.getElementById('answer1').innerHTML = "Hypertext blah";
	}

	function cssAcronym() {
		document.getElementById('answer2').innerHTML = "stylesheets yada";
	}

		$(document).ready(function(){
			$("#peek").click(function(){
				$(this).html("Here I am");
			});

		$("#change_paragraphs").click(function(){
			$("paragraph1").html("Replace text #1");
			$("paragraph2").html("Replace text #2");
		});


	});
</script>